src/hotspot/cpu/aarch64/assembler_aarch64.hpp, src/hotspot/cpu/aarch64/macroAssembler_aarch64.cpp, src/hotspot/cpu/aarch64/macroAssembler_aarch64.hpp, src/hotspot/cpu/aarch64/vtableStubs_aarch64.cpp
Async profiler shows that applications spend up to 10% in itable_stubs.
The generated itable_stub scans itable two times while it can be done in a single pass.
=> [Backport] 8307352: AARCH64: Improve itable_stub

src/hotspot/cpu/aarch64/aarch64.ad, src/hotspot/cpu/aarch64/c2_MacroAssembler_aarch64.cpp, src/hotspot/cpu/aarch64/c2_MacroAssembler_aarch64.hpp, src/hotspot/cpu/aarch64/vm_version_aarch64.cpp
The code to calculate a hash code consists of two parts: a vectorized loop of
Neon instruction that process 4 or 8 elements per iteration depending on the
data type and a fully unrolled scalar "loop" that processes up to 7 tail
elements.
=> [Backport] 8322770: Implement C2 VectorizedHashCode on AArch64

src/hotspot/share/opto/c2_globals.hpp, src/hotspot/share/opto/escape.cpp, src/hotspot/share/opto/memnode.cpp, src/hotspot/share/opto/parse1.cpp, src/hotspot/share/opto/stringopts.cpp, test/hotspot/jtreg/compiler/c2/irTests/ConstructorBarriers.java, test/hotspot/jtreg/compiler/lib/ir_framework/IRNode.java, test/micro/org/openjdk/bench/vm/compiler/ConstructorBarriers.java
The backport is not clean for two reasons:
The hunk in macro.cpp does not apply to JDK 21, because it was added later with [JDK-8287061](https://bugs.openjdk.org/browse/JDK-8287061)
The @Arguments style in IR test does not work in JDK 21, because the API was added later with [JDK-8324641](https://bugs.openjdk.org/browse/JDK-8324641)
Passed verification with full jtreg tests.
=> [Backport] 8300148: Consider using a StoreStore barrier instead of Release barrier on ctor exit

.github/workflows/build-cross-compile.yml
Summary: Fix sysroot creation failure in GHA
Testing: CI pipeline
Reviewers: sendaoYan, mmyxym
Issue: https://github.com/dragonwell-project/dragonwell21/issues/65
=> [Misc] Fix the workflow for building riscv

src/hotspot/cpu/aarch64/gc/g1/g1BarrierSetAssembler_aarch64.cpp, src/hotspot/cpu/x86/gc/g1/g1BarrierSetAssembler_x86.cpp, src/hotspot/share/gc/g1/c2/g1BarrierSetC2.cpp, src/hotspot/share/gc/g1/g1Arguments.cpp, src/hotspot/share/gc/g1/g1BarrierSet.cpp, src/hotspot/share/gc/g1/g1BarrierSet.inline.hpp, src/hotspot/share/gc/g1/g1CardTable.cpp, src/hotspot/share/gc/g1/g1RedirtyCardsQueue.cpp, src/hotspot/share/gc/g1/g1RedirtyCardsQueue.hpp, src/hotspot/share/gc/g1/g1RemSet.cpp, src/hotspot/share/gc/g1/g1YoungGCPostEvacuateTasks.cpp, src/hotspot/share/gc/g1/g1_globals.hpp, test/hotspot/jtreg/gc/arguments/TestG1ConcRefinementThreads.java
Summary: Provide option G1BarrierSimple to use simple G1 post barrier for better mutator performance
Testing: CI pipeline
Reviewers: yude, yifeng
Issue: https://github.com/dragonwell-project/dragonwell21/issues/56
=> [GC] Add option G1BarrierSimple to use simple g1 post barrier

src/hotspot/share/gc/g1/g1OopClosures.inline.hpp, src/hotspot/share/gc/g1/g1ParScanThreadState.cpp, src/hotspot/share/gc/parallel/psPromotionManager.cpp, src/hotspot/share/gc/parallel/psPromotionManager.inline.hpp, src/hotspot/share/gc/serial/defNewGeneration.cpp, src/hotspot/share/oops/markWord.hpp, src/hotspot/share/oops/oop.hpp, src/hotspot/share/oops/oop.inline.hpp
Summary: Backport
8316108: [Lilliput/JDK21] Cherry-pick: 8305898: Alternative self-forwarding mechanism
Differences with upstream pr 17755:
1. UseAltGCForwarding condition guards the critical parts of the change
2. The use of displaced_mark_helper is explained in https://github.com/openjdk/jdk/pull/13779/files#r1305779757
3. A test fix that only matters in 32-bit x86
4. Cosmetic changes
=> [Backport] 8316108: [Lilliput/JDK21] Cherry-pick: 8305898: Alternative self-forwarding mechanism

src/java.base/share/classes/java/text/DecimalFormatSymbols.java
[Backport] 8333462: Performance regression of new DecimalFormat() when compare to jdk11
Summary: The DecimalFormat constructor calls DecimalFormatSymbols.findNonFormatChar(String,char) multiple times, and the lambda implementation of findNonFormatChar  is slow than plain loop implementation.
Testing: All java.text.format jtreg.
Reviewers: D-D-H, Yude Lin
Issue: https://github.com/dragonwell-project/dragonwell21/issues/79
=> [Backport] 8333462: Performance regression of new DecimalFormat() when compare to jdk11

src/java.base/share/classes/java/text/CharacterIteratorFieldDelegate.java, src/java.base/share/classes/java/text/ChoiceFormat.java, src/java.base/share/classes/java/text/CompactNumberFormat.java, src/java.base/share/classes/java/text/DateFormat.java, src/java.base/share/classes/java/text/DecimalFormat.java, src/java.base/share/classes/java/text/DontCareFieldPosition.java, src/java.base/share/classes/java/text/FieldPosition.java, src/java.base/share/classes/java/text/Format.java, src/java.base/share/classes/java/text/MessageFormat.java, src/java.base/share/classes/java/text/NumberFormat.java, src/java.base/share/classes/java/text/SimpleDateFormat.java, src/java.base/share/classes/java/text/StringBufFactory.java, test/micro/org/openjdk/bench/java/text/DateFormatterBench.java, test/micro/org/openjdk/bench/java/text/MessageFormatterBench.java
[Backport] 8333396: Use StringBuilder internally for java.text.Format.* formatting
Summary: java.text.Format.* use StringBuffer internally, but StringBuffer's bad performance character become obvious after obsoleting biased locking. So use StringBuilder if possible in java.text.Formating.*.
Testing: All java.text.format jtreg.
Reviewers: D-D-H, Yude Lin
Issue: https://github.com/dragonwell-project/dragonwell21/issues/83
=> [Backport] 8333396: Use StringBuilder internally for java.text.Format.* formatting

make/RunTests.gmk, src/hotspot/share/runtime/arguments.cpp, test/hotspot/gtest/oops/test_arrayOop.cpp, test/hotspot/gtest/oops/test_objArrayOop.cpp, test/hotspot/jtreg/ProblemList-lilliput.txt
Backport the following test-only changes:
8316367: [Lilliput/JDK21] Provide infrastructure for Lilliput-specific ProblemList
8316442: [Lilliput/JDK21] Problem-list compiler/ciReplay tests
8319163: [Lilliput/JDK21] Fix arrayOopDesc gtest
8319135: [Lilliput] Fix objArrayOop gtest
Also backport the trivially easy to understand change:
8319524: [Lilliput] Only warn when compact headers are explicitly enabled
Additionally, disable compact object headers in JVMCI
=> [Backport] Lilliput test fixes and conditional option enabling

src/java.base/share/classes/java/io/ClassResolveCache.java, src/java.base/share/classes/java/io/ObjectInputStream.java, test/jdk/java/io/ObjectInputStream/PeekInputStreamTest.java, test/jdk/java/io/ObjectInputStream/ResolveProxyClass.java, test/jdk/java/io/ObjectInputStream/TestObjectStreamClass.java, test/micro/com/alibaba/bench/java/io/ObjectInputStreamTest.java
Summary:
Introduce fast serialization feature.
This feature can be enabled by -Dcom.alibaba.enableFastSerialization=true. Porting from https://github.com/dragonwell-project/dragonwell11/commit/bfdc9053ffbef1b062d6e5d4972f11b1e94cd4d6 and the origin author is yuleil
1. Create a ClassResolveCache to reduce calls to Class.forName(String)
2. Cache latestUserDefinedLoader(): The loader can be safely cached inside the ObjectInputStream class, once custom readObject() methods are invoked, the cache will be invalid.
For simple data objects, we can observe a 26% performance improvement. See com.alibaba.bench.java.io.ObjectInputStreamTest.
Reviewers: yuleil, kuaiwei
Testing: ObjectInputStream jtreg tests
Issue: https://github.com/dragonwell-project/dragonwell21/issues/76
=> [Misc] Fast serialization

src/hotspot/share/runtime/flags/allFlags.hpp, src/hotspot/share/runtime/globals.hpp, src/hotspot/share/runtime/globals_ext.hpp
Summary:
As we did in dragonwell 8 and 11, use globals_ext.hpp for dragonwell specific flags.
Testing: CI
Reviewers: Yude Lin, yueshi.zwj
Issue: https://github.com/dragonwell-project/dragonwell21/issues/93
=> [Misc] Add globals_ext.hpp for Dragonwell specific flags

src/java.base/share/classes/java/util/concurrent/ConcurrentHashMap.java, test/micro/org/openjdk/bench/java/util/concurrent/Maps.java
[Backport] 8322149: ConcurrentHashMap smarter presizing for copy constructor and putAll
Summary: ConcurrentHashMap::ConcurrentHashMap() -> putAll() -> tryPresize() -> transfer() does a lot of unnecessary work. There is nothing to transfer from the old table, since the table is just being initialized.
Reviewers: lingjun-cg, yuleil
Issue: https://github.com/dragonwell-project/dragonwell21/issues/101
=> [Backport] 8322149: ConcurrentHashMap smarter presizing for copy constructor and putAll

src/hotspot/share/opto/memnode.cpp, src/hotspot/share/opto/memnode.hpp, src/hotspot/share/opto/node.cpp, src/hotspot/share/opto/node.hpp, test/hotspot/jtreg/compiler/c2/irTests/scalarReplacement/ScalarReplacementWithGCBarrierTests.java, test/micro/org/openjdk/bench/java/util/concurrent/Maps.java
[Backport] 8333334: C2: Make result of `Node::dominates` more precise to enhance scalar replacement
Summary: This patch changes the algorithm of `Node::dominates` to make the result more precise, allows the iterators of `ConcurrentHashMap` to be scalar replaced, and makes the iteration ~30% faster.
Testing: CI testing, IR test
Reviewers: kuaiwei, JoshuaZhuwj
Issue: https://github.com/dragonwell-project/dragonwell21/issues/104
=> [Backport] 8333334: C2: Make result of Node::dominates more precise to enhance scalar replacement

src/hotspot/cpu/aarch64/aarch64.ad, src/hotspot/cpu/aarch64/aarch64_vector.ad, src/hotspot/cpu/aarch64/aarch64_vector_ad.m4, src/hotspot/cpu/aarch64/macroAssembler_aarch64.cpp, src/hotspot/cpu/aarch64/register_aarch64.hpp, src/hotspot/cpu/aarch64/vm_version_aarch64.cpp, src/hotspot/cpu/aarch64/vm_version_aarch64.hpp
Summary: This minor enhancement skips verify_sve_vector_length after native calls. It works on SVE micro-architecture that only supports 128-bit vector length.
Reviewers: MaxXSoft, Kuaiwei
Issue: https://github.com/dragonwell-project/dragonwell21/issues/106
=> [Backport] 8339063: [aarch64] Skip verify_sve_vector_length after native calls if SVE supports 128 bits VL only

src/hotspot/cpu/ppc/gc/z/zBarrierSetAssembler_ppc.cpp, src/hotspot/cpu/x86/gc/z/zBarrierSetAssembler_x86.cpp, src/hotspot/share/code/codeBlob.cpp, src/hotspot/share/code/codeBlob.hpp, src/hotspot/share/code/compiledMethod.cpp, src/hotspot/share/code/compiledMethod.hpp, src/hotspot/share/code/debugInfoRec.cpp, src/hotspot/share/code/dependencies.cpp, src/hotspot/share/code/nmethod.cpp, src/hotspot/share/code/nmethod.hpp, src/hotspot/share/compiler/compilerDefinitions.hpp, src/hotspot/share/jvmci/vmStructs_jvmci.cpp, src/hotspot/share/memory/heap.hpp, src/hotspot/share/opto/output.cpp, src/hotspot/share/prims/whitebox.cpp, src/hotspot/share/runtime/vmStructs.cpp, src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/code/CodeBlob.java, src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/code/NMethod.java, test/hotspot/jtreg/compiler/c1/TestLinearScanOrderMain.java
Summary: Include these changes
partial backport of 8329332: Remove CompiledMethod and CodeBlobLayout classes
[Backport] 8329433: Reduce nmethod header size
[Backport] 8331087: Move immutable nmethod data from CodeCache
[Backport] 8331253: 16 bits is not enough for nmethod::_skipped_instructions_size field
[Backport] 8333226: Regressions 2-3% in Compress ZGC after 8331253
Reviewers: Yude Lin, zhuoren.wz
Issue: https://github.com/dragonwell-project/dragonwell21/issues/88
=> [JIT] Backport changes to reduce nmethod size in code cache

test/jdk/tools/jlink/plugins/CDSPluginTest.java
Summary: jlink would not use COH if it's not on by default
Testing: tools/jlink/plugins/CDSPluginTest.java
Reviewers: mmyxym, lingjun-cg
Issue: https://github.com/dragonwell-project/dragonwell21/issues/128
Fix is suggested by: https://bugs.openjdk.org/browse/JDK-8341044
=> [Lilliput] Fix CDSPluginTest.java jlink not using COH

test/jdk/com/sun/jdi/EATests.java
Summary: Change unsupported test api
Testing: com/sun/jdi/EATests.java
Reviewers: mmyxym, jia-wei-tang
Issue: https://github.com/dragonwell-project/dragonwell21/issues/132
For unknown reason https://github.com/dragonwell-project/dragonwell21/pull/120/commits/de50f9439df04135821e80ffabdeec4e2ce9525b changes a test which caused failure. We change it back to be the same as jdk-tip.
=> [Lilliput] Test fix for EATests after backport

src/java.base/share/classes/java/lang/AbstractStringBuilder.java, src/java.base/share/classes/java/lang/StringConcatHelper.java, src/java.base/share/classes/java/lang/StringLatin1.java, src/java.base/share/classes/java/lang/StringUTF16.java, src/java.base/share/classes/java/lang/System.java, src/java.base/share/classes/java/lang/invoke/StringConcatFactory.java, src/java.base/share/classes/jdk/internal/access/JavaLangAccess.java, src/java.base/share/classes/jdk/internal/util/ClassFileDumper.java, test/hotspot/jtreg/compiler/patches/java.base/java/lang/Helper.java, test/micro/org/openjdk/bench/java/lang/StringBuilders.java
backport 我提交给OpenJDK关于字符串拼接的优化，由于有代码共用，所以也backport了优化StringBuilder.append(boolean/null)的优化 PR 19626。
https://github.com/openjdk/jdk/pull/19626 8333893: Optimization for StringBuilder append boolean & null
https://github.com/openjdk/jdk/pull/20253 8336831: Optimize StringConcatHelper.simpleConcat
https://github.com/openjdk/jdk/pull/20273 8336856: Efficient hidden class-based string concatenation strategy
https://github.com/openjdk/jdk/pull/20675 8338930: StringConcatFactory hardCoded string concatenation strategy
=> [Backport]String concatenation & StringBuilder appendNull/appendBoolean

src/hotspot/cpu/aarch64/gc/shared/barrierSetAssembler_aarch64.cpp, src/hotspot/share/runtime/globals_ext.hpp
Summary: In nmethod entry barrier, use lighter instruction.
Testing: CICD
Reviewers: mmyxym, kuaiwei
Issue: https://github.com/dragonwell-project/dragonwell21/issues/174
=> [JIT] Replace LoadLoad membar with load-acquire

src/hotspot/share/opto/live.cpp
Summary: Live in computation by PhaseLive results in always an empty live set. This doesn't cause any correctness issue but could affect performance.
Reviewers: Kuai Wei, Wang Zhuo
Issue: https://github.com/dragonwell-project/dragonwell21/issues/240
=> [Backport] 8345287: C2: live in computation is broken

src/hotspot/share/ci/ciMethod.cpp, src/hotspot/share/runtime/init.cpp
Summary: When building a zero/minimal JDK, C2 will be disabled, causing some native acceleration code to fail to compile. Such code should be disabled using conditional compilation.
Reviewers: kuaiwei, JoshuaZhuwj
Issue: https://github.com/dragonwell-project/dragonwell21/issues/252
=> [JIT] Fix compilation issues about native acceleration

test/hotspot/jtreg/compiler/alibaba/libAIExtTestEnvCall_1.c
Summary: AI-Extension unit `libAIExtTestEnvCall_1` accesses JVM flag with wrong API on aarch64, so it can not initialize properly. This patch fixes this issue.
Testing: test/hotspot/jtreg/compiler/alibaba/TestAIExtension.java
Reviewers: kuaiwei, JoshuaZhuwj
Issue: https://github.com/dragonwell-project/dragonwell21/issues/261
=> [JIT] Fix AI-Extension unit test initialization issue
